#!/bin/bash

# Check if both domain name and wordlist location are provided
if [ $# -ne 2 ]; then
    echo "Usage: $0 <domain_name> <wordlist_location>"
    exit 1
fi

domain="$1"
wordlist="$2"

# Iterate over each IP address from the wordlist and perform DNS lookup
for sub in $(cat "$wordlist"); do
    host "$sub.$domain"
done | grep -v "not found"


